server:
  port: ${PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: ${DLL_AUTO}
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  version: '0.0.1 Initial'
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMins: ${JWT_EXPIRE_MINS}
  
logging:
  level:
    root: ERROR
    com.eurekaconnect: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.*: ERROR
    org.springframework.jdbc.core: ERROR